name: Deploy ec2 using Terragrunt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up terragrunt
        uses: hashicorp/setup-terragrunt@v2
        with:
          terragrunt_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terragrunt Init
        run: terragrunt init

      - name: Terragrunt Plan
        run: terragrunt plan

      # - name: terragrunt Apply
      #   run: terragrunt apply -auto-approve